### ISSUE TITLE
Allow skipping userId and email for group calls

### ISSUE THREAD

**Issue by whatthewhat** [segment-integrations/integration-intercom#20]
Hey,
Wondering if you'd be open to allowing to skip `userId` and `email` for `group` calls?

The use case is calling `group` from the server to update some company properties (when the change was not triggered by a user).

**Comment by hankim813** [comment]
@whatthewhat Hi there -- super sorry for the late response... for future reference, for these kind of questions regarding features, it's best to contact the Segment support team at `friends@segment.com` :)

To answer your question, I think what you are trying to achieve can be done should be implemented in your server logic. You can simply make a `.group()` call when you need to update any company. You can find our [docs](https://segment.com/docs/integrations/intercom/#group) on how to do that.

Thanks!

**Comment by whatthewhat** [comment]
@hankim813 Hey, thanks for responding!

If I'm not mistaking (and it did work this way when I created the issue) `group` calls on the server still require a `user_id` or an `anonymous_id` to be present. In our use case the company property changes are not caused by a user and the `group` calls happen in a background job so there is no concept of a "current user". Currently we're hacking around this by always providing a "special" hardcoded user id, but that's definitely not ideal :)

I'll try to find some time to test if this is still the case and contact `friends@segment.com`

**Comment by hankim813** [comment]
@whatthewhat Despite `userId` not being required at the Segment API spec, as far as this integration goes, we have to use Intercom's Users Bulk Endpoint (by partner request). This means that we need a `userId` for each request we send to Intercom because we are actually updating the company profiles through a user's association with a given company. It is not ideal but something we can't really change until Intercom releases a similar Bulk api for Companies.

**Comment by whatthewhat** [comment]
I see, thanks for taking the time to explain this!
