### ISSUE TITLE
Avoid using the intercom bulk API endpoint when using group

### ISSUE THREAD

**Issue by sboichon** [segment-integrations/integration-intercom#33]
Hey guys !
Thanks for the integration !
I'm using the group method to create / update companies in _Intercom_ whenever our backend webhook is called from _Stripe_.
We have a lot of business logic regarding contacting customers in intercom and the fact that bulk api calls can take from a few hours up to a few days (confirmed by Intercom techs) is really problematic for us.
For now we found a semi-working workaround using the identify method.

Is there any reason for you to use specifically the bulk endpoint ? 
Can we hope to have a fix ?

**Comment by sperand-io** [comment]
hey @sboichon thanks so much for the flag and all the context in your note. 

A bit of backstory: we've moved to the bulk endpoints at Intercom’s request. These endpoints are  asynchronous and therefore more scalable, and the Bulk APIs are Intercom's preferred integration path for partners who write data into their platform for that reason.

However, we definitely hear your concern and are reaching out to Intercom to discuss this — will be sure to follow up here once we do.

**Comment by sboichon** [comment]
@sperand-io Thanks for the quick feedback and for taking time to discuss the issue with intercom.
I guess everybody would be happy if the group method could accept an optional parameter like 'direct' that would route the call on /users instead of /bulks/users. That's my 2cent suggestion.

**Comment by marcboscher** [comment]
@sperand-io been troubleshooting with Marshal from Intercom. Since the switch to the bulk endpoints we're having bismal performance on group/company updates, we're talking hours, like it's now been 8 hours since we last updated a few hundred companies and the update is not complete  yet. This is making the whole of Intercom useless because we cannot rely on its metrics for timely auto-messages.

Apparently, Intercom now has a separate logging backend or something for API calls from Segment, and they can't even list the bulk jobs completed or pended, created by Segment.

So we're in the dark. We send a group call to segment and have absolutely no way of knowing when it will update Intercom. 😢

**Comment by hankim813** [comment]
@marcboscher are you still having data latency issues?

**Comment by hankim813** [comment]
Will close this since we must use the Bulk endpoint for reasons @sperand-io has stated above.
